name: Build and Test Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image API
        run: docker build -t my-app-api:1.0.0 api/

      - name: Build image Mongo
        run: docker build -t my-app-mongo:1.0.0 mongo/
